import Navbar from "./Navbar";
import Footer from "./Footer";
import Head from "next/head";

export default function Layout({ children }: { children: any }) {
  return (
    <>
      <Head>
        <title>UNDERDOG/DATA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/underdogdata.svg" />
      </Head>
      <div className="max-w-7xl justify-center mx-auto">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </div>
    </>
  );
}
